version: "3.8"
services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  api:
    build:
      context: ./api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
